port={VOICECHAT_PORT}
bind_address=127.0.0.1
max_voice_distance=48.0
whisper_distance=24.0
codec=VOIP
mtu_size=900
tcp_rate_limit=16
keep_alive=1000
enable_groups=true
voice_host={VPS_IP}
allow_recording=true
spectator_interaction=false
spectator_player_possession=false
force_voice_chat=false
login_timeout=10000
broadcast_range=-1.0
allow_pings=true