pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // JitPack — required for MPAndroidChart
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "KodaNetwork"
include ':app'
